root <- normalizePath(getwd(), winslash="/")
.libPaths(c(file.path(root,"work/repro_decontx/rlibrary"),.libPaths()))
options(repos=c(CRAN="https://cloud.r-project.org"), timeout=90)
probe <- file.path(root,"work/repro_v3_cellchat_probe")
base <- jsonlite::read_json(file.path(probe,"R_dependency_resource_probe.json"), simplifyVector=TRUE)
ap <- available.packages(type="binary")
ip <- installed.packages()
missing <- base$missing_required
deps <- tools::package_dependencies(missing, db=ap, which=c("Depends","Imports","LinkingTo"), recursive=TRUE)
required <- sort(setdiff(unique(c(missing, unlist(deps))),c(rownames(ip),"R")))
unavailable <- setdiff(required,rownames(ap))
rows <- lapply(intersect(required,rownames(ap)),function(p) list(package=p,version=unname(ap[p,"Version"]),url=paste0(ap[p,"Repository"],"/",p,"_",ap[p,"Version"],".zip")))
out <- list(status="read_only_dependency_closure", R_version=R.version.string, direct_missing=missing, missing_dependency_count=length(required), unavailable_in_CRAN_binary=unavailable, missing_binary_dependencies=rows, no_installation=TRUE)
jsonlite::write_json(out,file.path(probe,"dependency_cost.json"),auto_unbox=TRUE,pretty=TRUE)
cat(jsonlite::toJSON(out,auto_unbox=TRUE,pretty=TRUE),"\n")
