"""Integrate completed sensitivity results and credit the known upstream fix."""
from pathlib import Path
import json
ROOT=Path(__file__).resolve().parent
PR='[LIANA PR #261](https://github.com/scverse/liana/pull/261)'
def load(p):return json.loads((ROOT/p).read_text(encoding='utf-8'))
def save(p,x):(ROOT/p).write_text(json.dumps(x,ensure_ascii=False,indent=2),encoding='utf-8')
def once(path,old,new):
    p=ROOT/path;s=p.read_text(encoding='utf-8')
    if new in s:return
    assert old in s,(path,old[:80])
    p.write_text(s.replace(old,new,1),encoding='utf-8')

front=load('repro_manuscript_frontmatter.json')
front['abstract_en']='Cross-cohort agreement of ligand–receptor expression effects can differ from agreement of inferred priority changes. We assessed astrocyte–endothelial candidates in two mouse cerebral ischemia cohorts (11 animal libraries), with an additional single-nucleus cohort reporting three biological replicates per group. Dependence-preserving label permutations, controlled aggregation diagnostics, fixed ranking universes and DecontX sensitivity analyses separated sources of disagreement. On the same 187 primary-selection candidates, expression coavailability agreed for 150/187 (80.2%; Spearman ρ=0.725), compared with 105/187 for native LIANA 1.10.0 priorities (56.1%; ρ=0.228). Ranking each distinct score column once increased priority correlation to 0.519; this diagnostic exactly reproduced the upstream aggregation correction merged on 9 September 2026. Fixing the global ranking universe yielded ρ=0.645 with more zero effects. Dynamic-gate expression concordance was 79.9% versus a 50.0% joint label-null median (exact P=0.005; six-test Holm P=0.030), while conditional validation P remained 0.10. DecontX reduced matched expression correlation from 0.725 to 0.641. On 99 candidates available across all 17 libraries, original-cohort expression concordance was 80/99, whereas comparisons involving the third cohort yielded 53/99 and 58/99 (ρ=0.551 and 0.576). Thus, the native expression–priority gap partly reflects a known aggregation implementation, while residual agreement depends on ranking context and cohort. This case study quantifies those consequences and supports separately auditing expression effects, prioritization and candidate eligibility.'
front['abstract_zh']='配体—受体表达效应的跨队列一致性可与推断优先级变化的一致性不同。本研究分析两个小鼠脑缺血队列的11个动物文库，并加入每组3个生物学重复的单核队列，通过保留依赖结构的标签置换、聚合诊断、固定排名母集和DecontX敏感性分析区分差异来源。在相同187条原规则候选上，表达共可用性为150/187同向（80.2%，ρ=0.725），原生LIANA 1.10.0优先级为105/187（56.1%，ρ=0.228）。每个独特评分列仅排名一次后ρ升至0.519；该诊断逐值复现了2026年9月9日已合并的上游聚合修正。固定全局排名母集后ρ为0.645，同时零效应增多。动态门槛表达同向率79.9%高于联合标签零分布中位数50.0%（精确P=0.005，6项Holm P=0.030），条件验证P仍为0.10。DecontX使匹配集合的表达相关由0.725降至0.641。在全部17个文库共同的99条候选上，原两队列表达同向80/99，涉及第三队列的比较为53/99和58/99（ρ=0.551和0.576）。原生表达—优先级差距部分源于已知聚合实现，剩余一致性仍依赖排名背景和队列。本案例量化这些影响，支持分别审计表达效应、候选优先级和表达资格。'
front['conclusion_en']='The original two cohorts showed higher expression-effect concordance than native LIANA 1.10.0 priority agreement. Controlled aggregation checks reproduced a known upstream correction and explained part of this gap; ranking context and ambient-count estimates contributed further sensitivity. On the same 99 candidates, expression agreement was 80/99 between the original cohorts and 53/99 or 58/99 with the third cohort. This case supports auditing expression effects, priority effects and candidate eligibility separately, with explicit software versions and directional denominators. Broader transfer and functional interpretation require independent evidence.'
front['conclusion_zh']='原两队列的表达效应一致性高于原生LIANA 1.10.0优先级一致性。受控聚合检查复现了已知上游修正并解释部分差距，排名背景和环境RNA估计带来进一步敏感性。在相同99条候选上，原两队列表达同向80/99，涉及第三队列时为53/99或58/99。本案例支持分别审计表达效应、优先级效应和候选资格，明确软件版本及方向分母。更广泛的转移和功能解释仍需独立证据。'
save('repro_manuscript_frontmatter.json',front)

zh=load('repro_main_sections.json');en=load('repro_manuscript_en_sections.json')
zh['methods_design']=[s.replace('完整标记面板、竞争类别、阈值及版本见补充方法。','完整标记面板、竞争类别、逐细胞分数及版本保存在归档配置与标签表。') for s in zh['methods_design']]
if not any('标准差下限0.25' in p for p in zh['methods_design']):
    zh['methods_design'].append('规则标签在每文库内计算：标记基因log1p(CP10k)按所有质控细胞标准化（总体标准差下限0.25），截断至−3到10，再对每谱系面板取平均。最高平均分≥0.5、与第二名差≥0.25且该谱系至少2个标记有原始计数时分配标签，否则保留未分配。星形面板为Aldh1l1、Slc1a3、Slc1a2、Gja1、Glul、Sox9、Aldoc；内皮面板为Pecam1、Cdh5、Esam、Tek、Erg、Vwf、Kdr。其余13个竞争谱系的固定面板同列于marker_panel.json；这些标签是规则操作定义。')
if not any('population-standard-deviation floor' in p for p in en['methods_design']):
    en['methods_design'].append('For rule assignment, marker log1p(CP10k) values were standardized across QC-passing cells within each library using a population-standard-deviation floor of 0.25, clipped to −3 to 10, and averaged within each lineage panel. Assignment required the highest mean score ≥0.5, a margin ≥0.25 over the second-highest panel, and at least two detected markers; remaining cells were unassigned. Astrocyte markers were Aldh1l1, Slc1a3, Slc1a2, Gja1, Glul, Sox9 and Aldoc; endothelial markers were Pecam1, Cdh5, Esam, Tek, Erg, Vwf and Kdr. Fixed panels for the other 13 competing lineages are retained in marker_panel.json. These are operational rule labels.')
for part,lang in [(zh,'zh'),(en,'en')]:
    if not any('PR #261' in p for p in part['introduction']):
        part['introduction'].append(('LIANA开发者已于2026年9月9日合并共用评分列重复排名的修正。'+PR+' 本研究将该已知修正作为明确的实现干预，量化其在真实缺血队列中的后果及修正后仍存在的背景依赖性；不以发现新的软件缺陷为贡献。') if lang=='zh' else ('LIANA developers merged a correction for repeated ranking of shared score columns on 9 September 2026. '+PR+' We use this known correction as a controlled intervention to quantify its consequences in ischemia cohorts and the remaining dependence on ranking context. The contribution is the reproducibility case study, rather than discovery of a new software defect.'))
    if not any('d421137' in p for p in part['methods_implementation']):
        part['methods_implementation'].append(('另从'+PR+'的固定合并提交d4211373692e7b9c10210488ccb1efe06452b097取得聚合函数，保存源码和SHA256，并在22份原始完整网络上独立执行，以逐值比较独特分数列诊断。仅核验聚合函数，未安装或重跑完整新版流程；原资源、显式expr_prop=0.1和表达分数保持不变，避免把同一上游变更中的默认检测门槛变化混入比较。') if lang=='zh' else ('We additionally retrieved the aggregation function at the fixed merge commit d4211373692e7b9c10210488ccb1efe06452b097 of '+PR+', retained source and SHA256, and executed it independently on all 22 raw complete networks for elementwise comparison with our unique-column diagnostic. This checks the aggregation function only, not a full newer pipeline release. The resource, explicit expr_prop=0.1 and expression scores were held unchanged; concurrent upstream changes to default detection thresholds were therefore excluded.'))
save('repro_main_sections.json',zh);save('repro_manuscript_en_sections.json',en)

# Keep the source citation grammatical in plain-text and Word rendering.
zh['introduction']=[('LIANA开发者已在'+PR+'中于2026年9月9日合并共用评分列重复排名的修正。本研究将该已知修正作为明确的实现干预，量化其在真实缺血队列中的后果及修正后仍存在的背景依赖性。') if s.startswith('LIANA开发者已') else s for s in zh['introduction']]
en['introduction']=[('LIANA developers merged a correction for repeated ranking of shared score columns on 9 September 2026 in '+PR+'. We use this known correction as a controlled intervention to quantify its consequences in ischemia cohorts and the remaining dependence on ranking context.') if s.startswith('LIANA developers merged') else s for s in en['introduction']]
save('repro_main_sections.json',zh);save('repro_manuscript_en_sections.json',en)

once('repro_results_static.md','### 固定排名背景','官方'+PR+'已在2026年9月9日修正同一重复排名行为。独立执行固定合并提交的聚合函数，在22份原始完整网络及187/174条目标候选上与本研究独特分数列诊断逐值完全一致，最大绝对误差为0。该结果将诊断明确对应到已知上游修正，同时保留了仅干预聚合步骤的解释范围。\n\n### 固定排名背景')
once('repro_manuscript_en_core.md','### Fixing the ranking universe',PR+' had already corrected this repeated-ranking behavior on 9 September 2026. Independently executing its fixed-commit aggregation function reproduced the unique-column diagnostic exactly on all 22 raw complete networks and the 187/174 targets (maximum absolute difference 0). This links the diagnostic to a known upstream correction while isolating the aggregation step from a complete newer release.\n\n### Fixing the ranking universe')
once('repro_discussion_zh.md','实现审计给出了最直接的解释。','实现审计给出了最直接的解释。同一行为已由开发者在'+PR+'中修正，本研究逐值复现该修正，量化其在本数据中的后果，并非首次报告该缺陷。')
once('repro_discussion_zh.md','新增每组3个生物学重复的第三队列扩展了外部证据，并显示同侧纹状体单核数据中的表达转移较弱。不同取材和测量方式对候选转移的影响，应通过继续扩充独立研究和报告完整失败边界来刻画。','新增每组3个生物学重复的第三队列扩展了外部证据。在相同99条候选上，原两队列表达同向80/99，第三队列与它们分别为53/99及58/99，描述性转移较弱。取材、单细胞或单核测量、平台及队列同时变化，本设计无法分别识别其影响；这些来源需要在更多独立研究中分层比较。')
once('repro_manuscript_en_core.md','The named diagnostic preserves this distinction from an official software release.','The diagnostic exactly matches the aggregation function of the known upstream correction in '+PR+'. It quantifies that correction\'s consequences while remaining distinct from a full newer-release rerun.')
once('repro_manuscript_en_core.md','Several limitations delimit interpretation.','The third cohort further limits transfer. On the same 99 candidates, expression signs agreed for 80/99 between the original cohorts but for 53/99 and 58/99 in comparisons involving the third study. Tissue region, nuclear versus cellular sampling, platform and study identity change together, so their individual contributions cannot be identified here. The extension provides a descriptive boundary for this case rather than a causal explanation of cohort differences.\n\nSeveral limitations delimit interpretation.')
once('repro_write_release_docs.py','No installed package was patched.','No installed package was patched. The known upstream fix was merged in [LIANA PR #261](https://github.com/scverse/liana/pull/261) on 2026-09-09. Its fixed-commit aggregation function exactly reproduced the unique-column diagnostic on all 22 raw networks; only this function, not a full newer release, was compared (`rank_upstream_*`). This case quantifies the correction\'s consequences and does not claim discovery of the defect.')
once('repro_write_release_docs.py','改题由实际实现诊断决定。','改题由实际实现诊断决定。[上游PR #261](https://github.com/scverse/liana/pull/261)已于2026年9月9日合并同一修正，固定提交聚合函数在22份原始网络逐值吻合；本文贡献是其后果和剩余敏感性的定量案例，不声称首次发现该缺陷。')
once('repro_write_release_docs.py','第三队列不替换或隐藏旧n=2结果。','在同一99条候选上，原两队列表达同向80/99，第三与它们为53/99和58/99（ρ=0.551/0.576）；同时变化的取材、测量和平台因素不能单独归因。第三队列不替换或隐藏旧n=2结果。')
caps=load('repro_caption_static.json')
if 'PR #261' not in caps['en']['Figure3']:
    caps['en']['Figure3']+=' The unique-column diagnostic exactly matched the isolated aggregation function of the known upstream correction in '+PR+' on the 22 raw networks; this is not a complete newer-release rerun.'
    caps['zh']['Figure3']+=' 独特分数列诊断在22份原始网络上逐值吻合已知上游修正'+PR+'的独立聚合函数，不代表完整新版流程重跑。'
save('repro_caption_static.json',caps)
print('Completed-result framing and known-upstream attribution integrated; English abstract words:',len(front['abstract_en'].split()))
